build: Require x11
Otherwise linking fails with:
/usr/bin/ld: xutils.o: undefined reference to symbol 'XGetWindowAttributes'
/usr/bin/ld: note: 'XGetWindowAttributes' is defined in DSO /lib/libX11.so.6 so try adding it to the linker command line